### ISSUE TITLE
Input channel unnamed or not found 

### ISSUE THREAD

**Issue by williamapardis** [whoidsl-mesobot/serial-lcm-bridge#1]
```
doc@frogDoctor:~ $ serial-lcm-bridge -b 19200 -vv /dev/ttyUSB0
initiator: 0x0a '
'
terminator: 0x0a '
'
opening serial port: /dev/ttyUSB0
opened serial port file stream with file descriptor 3
starting LCM
started LCM with file descriptor 4
input channel:
output channel: ttyUSB0o
created epoll 10
added serial port fd 3 to epoll
added LCM fd 4 to epoll
starting epoll loop
```

**Comment by williamapardis** [comment]
```
doc@frogDoctor:~ $ simple-serial-lcm-bridge -b 19200 -vv /dev/ttyUSB0
opening serial port: /dev/ttyUSB0
opened serial port with file descriptor 3
starting LCM
started LCM with file descriptor 4
input channel:
output channel: ttyUSB0o
created epoll 10
added serial port fd 3 to epoll
added LCM fd 4 to epoll
starting epoll loop
```

**Comment by williamapardis** [comment]
William was unable to successfully run the serial-LCM-bridge on his rasp pi in tandem with his dspl-lcm client/GUI daemon development. It appears the input channel of the bridge is not being displayed. The output channel (ttyUSB0o) appears to be working properly.

**Comment by bluesquall** [comment]
Confirmed working as expected on the `mb3` installed in mesobot yesterday, so this may be a pi-specific (or more recent kernel + toolchain) issue. It is still worth trying to track down.

**Comment by bluesquall** [comment]
Not reproducible on `Linux raspberrypi 6.1.21-v8+`.

Both input and output channel names are displayed, and transport both directions works with a null modem connecting two `ttyUSB` devices, as checked using the `./test-send_raw_bytes` utility.
